---
layout: cv
title: Scott Kishpaugh's CV
---
# Scott Kishpaugh 
BYU_Idaho Student, GIS major

<div id="webaddress">
<a href="https://byuidatascience.github.io/datascience_portfolio/">https://byuidatascience.github.io/datascience_portfolio/</a>
| <a href="https://byuidatascience.github.io/datascience_portfolio/">My Website</a>
</div>


## Currently
Attending BYU-Idaho as a GIS student 

### Specialized in
Programming, ArcGIS pro, ArcGIS online, Field maps. 

### Research interests
Reasearching ways that GIS can be uesful for compines by creating maps and gathering informaiton 
for a bussiness to makle a good decsion on how they can improve the quailty of thier work. 


## Education

`2022-2025`
__BYU_Idaho__, Rexburg ID

## Occupation
BYU-Idaho GIS intern
- Worked on campus as an intern doing various GIS projects creting maps using ArcGIS pro
- cretead a map of the sidewalks around campus using a GPS to collect data points and then 
using those points to draw in the idewalks around campus.
`2024`
__Idaho Falls public Works intern__, Idaho Falls 

- Worked as an intern collecting data for the water department.
- Created a GIS map for the water department. 
- used a GPS to collect data points of water lines and valuves to know exaclty where they are 
for locating purposes. 



<!-- ### Footer

Last updated: May 2013 -->